
name: release
on:
  push:
    tags:
    - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set env
      run: |
        echo "Extract version number from Tag"
        export VERSION=$(echo ${{ github.ref_name }} | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
    - name: Install helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.10.2'
      id: install
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: '${{ secrets.DOCKERHUB_USERNAME }}'
        password: '${{ secrets.DOCKERHUB_PASSWORD }}'
    - name: Install GPG Helm plugin
      run: |
        helm plugin install https://github.com/KrishnaIyer/helm-gpg
    - name: Import the signing key
      run: |
        echo -n ${{ secrets.GPG_SIGNING_KEY }} | base64 --decode > priv.key
        printf '%s' '${{ secrets.GPG_SIGNING_PASSPHRASE }}' >/tmp/gpg_passphrase
        cat /tmp/gpg_passphrase | gpg --passphrase-fd 0 --no-tty --batch --import priv.key
    - name: Package helm and push
      run: |
        echo Release version ${{ env.RELEASE_VERSION }}
        make helm.build
        ./signchart.sh http-dev-server-helm-${{ env.RELEASE_VERSION }}.tgz ${{ secrets.GPG_SIGNING_KEY_ID }}
        OCI_TAG=${{ env.RELEASE_VERSION }} make helm.push

