
name: release
on:
  push:
    tags:
    - '*'
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '~1.19'
    - name: Download Go dependencies
      run: |
        pushd util/signature
        go mod download && go mod tidy
        popd
    - name: Set env
      run: |
        echo "Extract version number from Tag"
        export VERSION=$(echo ${{ github.ref_name }} | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
    - name: Install helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.10.2'
      id: install
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: '${{ secrets.DOCKERHUB_USERNAME }}'
        password: '${{ secrets.DOCKERHUB_PASSWORD }}'
    - name: Get the signing key
      run: |
        echo -n ${{ secrets.GPG_SIGNING_KEY }} | base64 --decode > /tmp/priv.key
    - name: Package Helm charts, sign and push
      run: |
        echo Release version ${{ env.RELEASE_VERSION }}
        make helm.build
        export GPG_PASSPHRASE=${{ secrets.GPG_SIGNING_PASSPHRASE }}
        export GPG_KEY_FILE=/tmp/priv.key
        OCI_TAG=${{ env.RELEASE_VERSION }} make helm.sign
        OCI_TAG=${{ env.RELEASE_VERSION }} make helm.push

