
name: release
on:
  push:
    tags:
    - '*'
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set env
      run: |
        echo "Extract version number from Tag"
        export VERSION=$(echo ${{ github.ref_name }} | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
        echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
    - name: Install helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.10.2'
      id: install
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: '${{ secrets.DOCKERHUB_USERNAME }}'
        password: '${{ secrets.DOCKERHUB_PASSWORD }}'
    - name: Import the signing key
      run: |
        echo -n ${{ secrets.GPG_SIGNING_KEY }} | base64 --decode > priv.key
        printf '%s' '${{ secrets.GPG_SIGNING_PASSPHRASE }}' >/tmp/gpg_passphrase
        cat /tmp/gpg_passphrase | gpg --passphrase-fd 0 --no-tty --batch --import priv.key
    - name: Package helm and push
      run: |
        GPG_TTY=$(tty)
        export GPG_TTY
        echo Release version ${{ env.RELEASE_VERSION }}
        make helm.build
        chart=http-dev-server-helm-${{ env.RELEASE_VERSION }}.tgz
        echo "Sign helm chart package $chart"
        shasum=$(openssl dgst -sha256 $chart | awk '{ print $2 }')
        chartyaml=$(tar -zxf $chart --exclude 'charts/' --wildcards -O '*/Chart.yaml')
        c=$(cat << EOF
        $chartyaml

        ...
        files:
          $chart: sha256:$shasum
        EOF
        )
        echo "$c" | gpg --clearsign -o "$chart.prov" -u ${{ secrets.GPG_SIGNING_KEY_ID }}
        OCI_TAG=${{ env.RELEASE_VERSION }} make helm.push

